struct CMD_FLASH
{
	enum
	{
		CMD_INFOCODE_ACK = 1000,		/*服务端返回通用消息*/
		CMD_LOGIN_REQ = 1001,		/*login*/
		CMD_REGIST_REQ = 1002,		/*注册*/
		CMD_MATCHROUNTINFO_REQ = 1003,		/*获取比赛数据*/
		CMD_MATCHROUNTINFO_ACK = 1004,		/*比赛回合信息*/
		CMD_MATCHSTATISTICSINFO_REQ = 1005,		/*请求统计数据*/
		CMD_MATCHSTATISTICSINFO_ACK = 1006,		/*返回统计数据*/
		CMD_MATCHENVIINFO_REQ = 1007,		/*比赛初始化获取比赛环境请求*/
		CMD_MATCHENVIINFO_ACK = 1008,		/*比赛环境信息*/
		CMD_MATCHINITTEAMINFO_REQ = 1009,		/*比赛初始化获取球队概要信息*/
		CMD_MATCHINITTEAMINFO_ACK = 1010,		/*球队概要信息*/
		CMD_MATCHINITPLAYER_REQ = 1011,		/*球员信息初始化请求*/
		CMD_MATCHINITPLAYER_ACK = 1012,		/*球员初始化信息*/
		CMD_MATCHPLAYERANSYINFO_REQ = 1013,		/*球员动态信息请求*/
		CMD_MATCHPLAYERANSYINFO_ACK = 1014,		/*球员动态信息*/
		CMD_MATCHINITCARD_REQ = 1015,		/*请求比赛卡牌信息*/
		CMD_MATCHINITCARD_ACK = 1016,		/*比赛卡牌信息*/
		CMD_CHANGETACTICALCARD_REQ = 1017,		/*换战术卡*/
		CMD_CHANGEPLAYER_REQ = 1018,		/*换人*/
		CMD_MATCHTEAMANSYINFO_REQ = 1019,		/*球队比赛信息*/
		CMD_MATCHTEAMANSYINFO_ACK = 1020,		/*球队比赛信息*/
		CMD_SPECIFIEDROLE_REQ = 1021,		/*请求指定特定球员角色*/
		CMD_SETTRUSTEESHIP_REQ = 1022,		/*请求指定当前托管模式*/
		CMD_HEARTBEAT_REQ = 1023,		/*心跳*/
		CMD_MATCHSTARTSTATUS_REQ = 1024,		/*比赛可播放状态*/

		CMD_INFOCODE_ACK_AA_ME = 6000,
		CMD_LOGIN_REQ_AA_ME = 6001,
		CMD_REGIST_REQ_AA_ME = 6002,
		CMD_MATCHROUNTINFO_REQ_AA_ME = 6003,
		CMD_MATCHROUNTINFO_ACK_AA_ME = 6004,
		CMD_MATCHSTATISTICSINFO_REQ_AA_ME = 6005,
		CMD_MATCHSTATISTICSINFO_ACK_AA_ME = 6006,
		CMD_MATCHENVIINFO_REQ_AA_ME = 6007,
		CMD_MATCHENVIINFO_ACK_AA_ME = 6008,
		CMD_MATCHINITTEAMINFO_REQ_AA_ME = 6009,
		CMD_MATCHINITTEAMINFO_ACK_AA_ME = 6010,
		CMD_MATCHINITPLAYER_REQ_AA_ME = 6011,
		CMD_MATCHINITPLAYER_ACK_AA_ME = 6012,
		CMD_MATCHPLAYERANSYINFO_REQ_AA_ME = 6013,
		CMD_MATCHPLAYERANSYINFO_ACK_AA_ME = 6014,
		CMD_MATCHINITCARD_REQ_AA_ME = 6015,
		CMD_MATCHINITCARD_ACK_AA_ME = 6016,
		CMD_CHANGETACTICALCARD_REQ_AA_ME = 6017,
		CMD_CHANGEPLAYER_REQ_AA_ME = 6018,
		CMD_MATCHTEAMANSYINFO_REQ_AA_ME = 6019,
		CMD_MATCHTEAMANSYINFO_ACK_AA_ME = 6020,
		CMD_SPECIFIEDROLE_REQ_AA_ME = 6021,
		CMD_SETTRUSTEESHIP_REQ_AA_ME = 6022,
		CMD_HEARTBEAT_REQ_AA_ME = 6023,
		CMD_MATCHSTARTSTATUS_REQ_AA_ME = 6024,

		CMD_INFOCODE_ACK_ME_AA = 11000,
		CMD_LOGIN_REQ_ME_AA = 11001,
		CMD_REGIST_REQ_ME_AA = 11002,
		CMD_MATCHROUNTINFO_REQ_ME_AA = 11003,
		CMD_MATCHROUNTINFO_ACK_ME_AA = 11004,
		CMD_MATCHSTATISTICSINFO_REQ_ME_AA = 11005,
		CMD_MATCHSTATISTICSINFO_ACK_ME_AA = 11006,
		CMD_MATCHENVIINFO_REQ_ME_AA = 11007,
		CMD_MATCHENVIINFO_ACK_ME_AA = 11008,
		CMD_MATCHINITTEAMINFO_REQ_ME_AA = 11009,
		CMD_MATCHINITTEAMINFO_ACK_ME_AA = 11010,
		CMD_MATCHINITPLAYER_REQ_ME_AA = 11011,
		CMD_MATCHINITPLAYER_ACK_ME_AA = 11012,
		CMD_MATCHPLAYERANSYINFO_REQ_ME_AA = 11013,
		CMD_MATCHPLAYERANSYINFO_ACK_ME_AA = 11014,
		CMD_MATCHINITCARD_REQ_ME_AA = 11015,
		CMD_MATCHINITCARD_ACK_ME_AA = 11016,
		CMD_CHANGETACTICALCARD_REQ_ME_AA = 11017,
		CMD_CHANGEPLAYER_REQ_ME_AA = 11018,
		CMD_MATCHTEAMANSYINFO_REQ_ME_AA = 11019,
		CMD_MATCHTEAMANSYINFO_ACK_ME_AA = 11020,
		CMD_SPECIFIEDROLE_REQ_ME_AA = 11021,
		CMD_SETTRUSTEESHIP_REQ_ME_AA = 11022,
		CMD_HEARTBEAT_REQ_ME_AA = 11023,
		CMD_MATCHSTARTSTATUS_REQ_ME_AA = 11024,
	};
};